create table  car3(
    car_id BIGSERIAL NOT NULL,
	make VARCHAR(50),
	model VARCHAR(50),
	price INT,
	person_id INT,
	PRIMARY KEY (car_id)
);


insert into car3 (make, model, price) values ('Tesla', 'Model X', 50000);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'GTI', 14410, 545);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Cherokee', 9940, 747);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 3500', 30862, 57);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 43407, 212);
insert into car3 (make, model, price, person_id) values ('Honda', 'Accord', 5975, 801);
insert into car3 (make, model, price, person_id) values ('BMW', 'X3', 2320, 425);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'I', 2915, 336);
insert into car3 (make, model, price, person_id) values ('Ford', 'Expedition', 47142, null);
insert into car3 (make, model, price, person_id) values ('GMC', '2500 Club Coupe', 33447, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MPV', 21136, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege5', 5924, 580);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'MKX', 49417, 456);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 2500', 2719, 599);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 48485, null);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 46921, 733);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 3500', 39420, 250);
insert into car3 (make, model, price, person_id) values ('Acura', 'RL', 35118, 246);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'CC', 7673, 831);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Bonneville', 9524, 434);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Forenza', 19795, 382);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra', 16309, 463);
insert into car3 (make, model, price, person_id) values ('Acura', 'RL', 4374, 528);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Avalanche 2500', 1829, 191);
insert into car3 (make, model, price, person_id) values ('Audi', 'A4', 19007, 488);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Maxima', 8518, 339);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Cutlass Supreme', 13750, 70);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Lumina', 36346, 242);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy', 35274, 46);
insert into car3 (make, model, price, person_id) values ('Lamborghini', 'Gallardo', 30848, 673);
insert into car3 (make, model, price, person_id) values ('Volvo', 'C70', 4069, 353);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 31663, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'GTO', 34246, 557);
insert into car3 (make, model, price, person_id) values ('Audi', 'A6', 13472, 223);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'C-Class', 38083, 118);
insert into car3 (make, model, price, person_id) values ('Citroën', 'SM', 36907, 816);
insert into car3 (make, model, price, person_id) values ('Plymouth', 'Sundance', 17216, 653);
insert into car3 (make, model, price, person_id) values ('Ford', 'GT500', 10644, 910);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Pacifica', 6671, 90);
insert into car3 (make, model, price, person_id) values ('Acura', 'TSX', 13211, 734);
insert into car3 (make, model, price, person_id) values ('Audi', 'TT', 2195, null);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Passat', 44629, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 42052, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer', 30331, 626);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express', 31863, 465);
insert into car3 (make, model, price, person_id) values ('BMW', '760', 29655, 829);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Jetta', null, 155);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Metro', 47774, 598);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 2603, 496);
insert into car3 (make, model, price, person_id) values ('Ford', 'E-350 Super Duty', null, 842);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Impreza', null, 421);
insert into car3 (make, model, price, person_id) values ('Ford', 'Bronco II', 43621, 287);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 29704, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 28349, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Tahoe', 23790, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LS', null, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege', 44845, 42);
insert into car3 (make, model, price, person_id) values ('Hummer', 'H3T', 7937, 670);
insert into car3 (make, model, price, person_id) values ('Lexus', 'GS', 42331, 341);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota Club', 11391, 18);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Frontier', 23634, 649);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Fox', 2894, 43);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Galant', 22480, 492);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'New Beetle', null, null);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Accent', 45800, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'IS-F', null, 289);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'G6', null, 52);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 17982, 164);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Avalon', 20046, 857);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Arnage', 36710, 16);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 20093, 523);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tacoma', 9188, null);
insert into car3 (make, model, price, person_id) values ('Saab', '9000', 26271, 114);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Land Cruiser', 40639, 839);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mariner', 35774, 116);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'CLK-Class', 29372, 543);
insert into car3 (make, model, price, person_id) values ('Buick', 'Lucerne', 17666, 948);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'GTI', 15056, 298);
insert into car3 (make, model, price, person_id) values ('Maybach', '57', 13115, 89);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'JX', 16936, 550);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'K5 Blazer', 39270, 561);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Montana', 23163, 134);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LS', 2522, null);
insert into car3 (make, model, price, person_id) values ('Saab', '900', 25631, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Escort', 42877, 718);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Bravada', 1651, 391);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E150', null, 305);
insert into car3 (make, model, price, person_id) values ('Buick', 'Skylark', 24693, 378);
insert into car3 (make, model, price, person_id) values ('Ford', 'Tempo', 7324, 515);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E350', 5999, 483);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 46440, 264);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SLK-Class', null, 761);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Celica', 16125, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 50', 37160, 602);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express 3500', 26157, 111);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 23420, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 15131, 871);
insert into car3 (make, model, price, person_id) values ('Buick', 'Verano', 12178, 927);
insert into car3 (make, model, price, person_id) values ('Plymouth', 'Prowler', 37762, 717);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E350', 8082, 246);
insert into car3 (make, model, price, person_id) values ('Volvo', 'C30', 36362, 260);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Town Car', null, 644);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G', 17320, 382);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 35123, 260);
insert into car3 (make, model, price, person_id) values ('MINI', 'Clubman', 14829, 520);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 1500', 9645, 296);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'GTI', 39449, 412);
insert into car3 (make, model, price, person_id) values ('Honda', 'del Sol', 45062, 402);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'FX', 44411, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Prius v', 3474, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'E-Series', 18642, 335);
insert into car3 (make, model, price, person_id) values ('BMW', 'M3', 9421, 820);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'riolet', 37025, 664);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Grand Vitara', 31117, 866);
insert into car3 (make, model, price, person_id) values ('Ford', 'E150', 15640, 282);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 47662, 479);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Pathfinder', 11747, 263);
insert into car3 (make, model, price, person_id) values ('BMW', 'M5', 12159, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express 1500', 24122, 116);
insert into car3 (make, model, price, person_id) values ('GMC', 'Savana 3500', 33143, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Sable', 5641, 143);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 41832, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cobalt', 19665, 614);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', null, 440);
insert into car3 (make, model, price, person_id) values ('Ford', 'E-Series', 48309, 156);
insert into car3 (make, model, price, person_id) values ('Toyota', 'FJ Cruiser', 16160, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 20173, 887);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sportage', null, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'SC', 49531, 184);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 28320, 344);
insert into car3 (make, model, price, person_id) values ('Buick', 'Regal', null, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'CX-7', 32643, 449);
insert into car3 (make, model, price, person_id) values ('Lexus', 'RX', 48030, 906);
insert into car3 (make, model, price, person_id) values ('Lamborghini', 'Diablo', 15582, 706);
insert into car3 (make, model, price, person_id) values ('BMW', 'X5', 32760, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B-Series', 31165, 699);
insert into car3 (make, model, price, person_id) values ('Ford', 'F250', 35406, 346);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 8151, 629);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Intrepid', 32523, 874);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sedona', 26582, 419);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Cayenne', 33357, 408);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy XL', null, 439);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E350', 20797, 838);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Cutlass Supreme', 2592, 740);
insert into car3 (make, model, price, person_id) values ('MINI', 'Clubman', 27786, 775);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Previa', 19780, 427);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Tribute', 16316, 800);
insert into car3 (make, model, price, person_id) values ('Audi', 'V8', null, null);
insert into car3 (make, model, price, person_id) values ('Plymouth', 'Grand Voyager', 32830, 25);
insert into car3 (make, model, price, person_id) values ('Saturn', 'L-Series', 34342, 335);
insert into car3 (make, model, price, person_id) values ('BMW', 'X5', 30857, 909);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Endeavor', 40511, 617);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cavalier', 10803, 267);
insert into car3 (make, model, price, person_id) values ('Chrysler', '300', 1145, 507);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Jetta', 22481, 411);
insert into car3 (make, model, price, person_id) values ('Audi', 'A5', 42942, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'CL-Class', 21386, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer Sport Trac', 39361, null);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'QX', 33277, 36);
insert into car3 (make, model, price, person_id) values ('Buick', 'Riviera', 47480, 143);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Arnage', 34692, 276);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Montero Sport', 29773, 836);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Spirit', 27606, 294);
insert into car3 (make, model, price, person_id) values ('BMW', '525', 28092, 17);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Bravada', 22143, 69);
insert into car3 (make, model, price, person_id) values ('GMC', 'Savana 3500', 26537, 243);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mariner', null, 889);
insert into car3 (make, model, price, person_id) values ('Toyota', 'T100', 34111, 5);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LX', null, null);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Grand Vitara', 17621, null);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Lancer Evolution', 5516, 384);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Wrangler', 1716, 396);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Achieva', 2390, 508);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Eclipse', 4970, 381);
insert into car3 (make, model, price, person_id) values ('BMW', 'Z4', 38493, null);
insert into car3 (make, model, price, person_id) values ('Mazda', '929', null, null);
insert into car3 (make, model, price, person_id) values ('Maserati', 'GranTurismo', 34845, 367);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'GTO', 32699, 823);
insert into car3 (make, model, price, person_id) values ('Ford', 'Tempo', 13970, null);
insert into car3 (make, model, price, person_id) values ('Acura', 'Integra', 22219, 203);
insert into car3 (make, model, price, person_id) values ('Acura', 'Legend', 44170, 447);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Am', 33909, 537);
insert into car3 (make, model, price, person_id) values ('Nissan', 'JUKE', null, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 2500', 35934, 5);
insert into car3 (make, model, price, person_id) values ('Ford', 'Thunderbird', 21160, 775);
insert into car3 (make, model, price, person_id) values ('Saab', '9-5', 15187, 200);
insert into car3 (make, model, price, person_id) values ('BMW', '5 Series', 44217, 291);
insert into car3 (make, model, price, person_id) values ('Mazda', 'RX-7', 23219, 484);
insert into car3 (make, model, price, person_id) values ('Scion', 'xA', 3992, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'F250', 20640, 405);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix Turbo', 3655, null);
insert into car3 (make, model, price, person_id) values ('Buick', 'Skylark', 19317, 690);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Durango', 31530, 416);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer', null, null);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Continental', 29954, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', 49435, 711);
insert into car3 (make, model, price, person_id) values ('Ford', 'Expedition', 7831, 623);
insert into car3 (make, model, price, person_id) values ('Ford', 'Mustang', 17659, 169);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Passat', 34119, 630);
insert into car3 (make, model, price, person_id) values ('Maserati', '430', 7142, null);
insert into car3 (make, model, price, person_id) values ('Ram', '2500', 7231, 471);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 25933, 207);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazda6', null, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express', 23092, 892);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Scirocco', 38464, null);
insert into car3 (make, model, price, person_id) values ('BMW', '1 Series', 34047, 736);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'G-Series G10', 36706, 757);
insert into car3 (make, model, price, person_id) values ('Ford', 'Escort', 26794, 924);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'W126', 41965, 657);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Prizm', 49766, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'S10', 27339, 759);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Sidekick', 12721, 736);
insert into car3 (make, model, price, person_id) values ('Ford', 'Ranger', 33768, 390);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mystique', 1805, 936);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 3708, 440);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 1500', 32497, 412);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado', 17713, 874);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'XK', 41253, null);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Titan', null, null);
insert into car3 (make, model, price, person_id) values ('Scion', 'xD', 14808, 600);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazda6', null, 845);
insert into car3 (make, model, price, person_id) values ('Kia', 'Mohave/Borrego', 11345, 89);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover Sport', 29155, 129);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Carrera GT', 44891, 347);
insert into car3 (make, model, price, person_id) values ('Ferrari', '612 Scaglietti', 31604, 816);
insert into car3 (make, model, price, person_id) values ('Lexus', 'GS', 5036, 220);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Town Car', 30069, 801);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sedona', null, 154);
insert into car3 (make, model, price, person_id) values ('Chrysler', '300M', 37718, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'A6', 36520, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Land Cruiser', 30952, 938);
insert into car3 (make, model, price, person_id) values ('Rolls-Royce', 'Phantom', 38626, 869);
insert into car3 (make, model, price, person_id) values ('Hummer', 'H1', 14227, null);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Sonata', 1153, 599);
insert into car3 (make, model, price, person_id) values ('Ford', 'Falcon', 40986, 522);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Pathfinder', 11014, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B-Series', 10264, 180);
insert into car3 (make, model, price, person_id) values ('Volvo', 'XC60', 14812, 200);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Sunbird', 10651, 843);
insert into car3 (make, model, price, person_id) values ('Honda', 'Fit', 8956, 405);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Montero', 21470, 616);
insert into car3 (make, model, price, person_id) values ('GMC', 'Jimmy', 30303, 946);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Liberty', 46277, 866);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 44459, 259);
insert into car3 (make, model, price, person_id) values ('Audi', 'TT', 37083, null);
insert into car3 (make, model, price, person_id) values ('Subaru', 'SVX', 41984, 227);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 1500', 20361, 22);
insert into car3 (make, model, price, person_id) values ('Saturn', 'Ion', null, 900);
insert into car3 (make, model, price, person_id) values ('Ford', 'Contour', 24774, 765);
insert into car3 (make, model, price, person_id) values ('Ford', 'LTD', 27664, null);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Sentra', 35535, 191);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 13563, 578);
insert into car3 (make, model, price, person_id) values ('GMC', 'Yukon XL 2500', 26373, 401);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy XUV', 24549, 922);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 6086, 458);
insert into car3 (make, model, price, person_id) values ('Buick', 'LeSabre', 9012, 265);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', 18299, 588);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'CL-Class', 43989, 768);
insert into car3 (make, model, price, person_id) values ('Porsche', '911', 46600, 647);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Impreza', 19391, 913);
insert into car3 (make, model, price, person_id) values ('GMC', 'Vandura 2500', 3939, 604);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 11761, 323);
insert into car3 (make, model, price, person_id) values ('Buick', 'Verano', 45256, 339);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Navigator', 12307, 632);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Continental', 32616, 64);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Cirrus', 12876, 917);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Outlander', null, null);
insert into car3 (make, model, price, person_id) values ('Buick', 'Century', 18589, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tacoma Xtra', 7655, 563);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', 38332, null);
insert into car3 (make, model, price, person_id) values ('Buick', 'Reatta', 44986, 251);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 15780, 317);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Capri', 4033, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy', 8694, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'Allroad', 17998, 280);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Trans Sport', 47720, 290);
insert into car3 (make, model, price, person_id) values ('Pontiac', '6000', 15037, 14);
insert into car3 (make, model, price, person_id) values ('MINI', 'Cooper', 39166, 88);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Passat', 28686, 615);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover Classic', null, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Canyon', 34328, 140);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', null, 477);
insert into car3 (make, model, price, person_id) values ('Lotus', 'Exige', null, null);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', null, null);
insert into car3 (make, model, price, person_id) values ('Volvo', 'S40', 6832, 306);
insert into car3 (make, model, price, person_id) values ('Honda', 'Element', 11325, 233);
insert into car3 (make, model, price, person_id) values ('Ford', 'Windstar', 25748, 120);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', 24923, 410);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '500SEL', 32606, 563);
insert into car3 (make, model, price, person_id) values ('GMC', 'Savana 1500', 8349, 844);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corsica', 32479, 608);
insert into car3 (make, model, price, person_id) values ('Acura', 'MDX', 22806, 528);
insert into car3 (make, model, price, person_id) values ('Ford', 'Flex', 15668, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy', 32981, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'CLS-Class', 29394, 252);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Challenger', 29444, 771);
insert into car3 (make, model, price, person_id) values ('Acura', 'TL', 30419, 76);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'FX', 16785, 496);
insert into car3 (make, model, price, person_id) values ('Maserati', 'Gran Sport', 49286, 167);
insert into car3 (make, model, price, person_id) values ('Ford', 'Thunderbird', 25558, 891);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sephia', 36609, 251);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Suburban 1500', 13155, 233);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Navigator L', 30434, null);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 12719, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Bonneville', 31895, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'E250', 42627, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Excursion', 44056, 248);
insert into car3 (make, model, price, person_id) values ('Ford', 'Thunderbird', 8628, 782);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege', null, null);
insert into car3 (make, model, price, person_id) values ('GMC', '1500', null, 200);
insert into car3 (make, model, price, person_id) values ('Saab', '9-4X', 42106, 189);
insert into car3 (make, model, price, person_id) values ('BMW', '530', 29338, 343);
insert into car3 (make, model, price, person_id) values ('MINI', 'Cooper', null, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Challenger', 40086, 705);
insert into car3 (make, model, price, person_id) values ('Mazda', 'RX-7', 38058, 687);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 2500', 21355, 928);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Galant', 8134, 673);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Stylus', 33891, 727);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 2851, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'SC', 18177, 833);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Chariot', 8021, 864);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mariner', 42529, 306);
insert into car3 (make, model, price, person_id) values ('Ford', 'F250', 40865, 80);
insert into car3 (make, model, price, person_id) values ('Audi', 'S5', 38872, 484);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', null, 16);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Wrangler', 13162, 614);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Celica', 44241, 207);
insert into car3 (make, model, price, person_id) values ('Toyota', 'RAV4', 38021, 440);
insert into car3 (make, model, price, person_id) values ('Lotus', 'Esprit', 38509, 259);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Intrepid', 6341, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Tahoe', 10850, 627);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Solara', 27141, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Sebring', 2646, 449);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'PT Cruiser', null, 798);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota Club', 32984, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-6', 47151, 180);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Jetta', 19051, 125);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 8273, null);
insert into car3 (make, model, price, person_id) values ('BMW', 'M3', 49342, 20);
insert into car3 (make, model, price, person_id) values ('Toyota', 'FJ Cruiser', 29855, 495);
insert into car3 (make, model, price, person_id) values ('Honda', 'Civic', 13166, 558);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Diamante', 24580, null);
insert into car3 (make, model, price, person_id) values ('Lamborghini', 'Murciélago', null, null);
insert into car3 (make, model, price, person_id) values ('Hillman', 'Minx Magnificent', 9557, null);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Discovery', 20061, null);
insert into car3 (make, model, price, person_id) values ('BMW', 'X5', 6954, 34);
insert into car3 (make, model, price, person_id) values ('Corbin', 'Sparrow', 30212, null);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Veloster', 12304, 539);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'X-Type', 27535, 664);
insert into car3 (make, model, price, person_id) values ('Lexus', 'GS', 42030, null);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Amigo', 46129, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', 26718, 790);
insert into car3 (make, model, price, person_id) values ('Maserati', 'Quattroporte', 35612, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'LeMans', 20968, 590);
insert into car3 (make, model, price, person_id) values ('Ford', 'F250', 19399, 374);
insert into car3 (make, model, price, person_id) values ('Lexus', 'GS', 18356, 339);
insert into car3 (make, model, price, person_id) values ('Ford', 'Contour', 2076, 245);
insert into car3 (make, model, price, person_id) values ('Saturn', 'VUE', 10658, 643);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'M', 14735, 876);
insert into car3 (make, model, price, person_id) values ('Saturn', 'Relay', 3581, 313);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Accent', 4884, 939);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Sienna', 3569, 50);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'SJ', 12048, null);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Continental Super', 49291, 257);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Cherokee', 24217, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Am', 4608, 351);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 16009, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SLS AMG', null, 768);
insert into car3 (make, model, price, person_id) values ('Buick', 'Regal', 7391, 64);
insert into car3 (make, model, price, person_id) values ('Pontiac', '6000', 47695, 317);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'LeMans', 5363, 630);
insert into car3 (make, model, price, person_id) values ('Honda', 'Element', 30094, 503);
insert into car3 (make, model, price, person_id) values ('Chevrolet', '2500', 46011, 666);
insert into car3 (make, model, price, person_id) values ('Buick', 'LeSabre', null, 283);
insert into car3 (make, model, price, person_id) values ('Audi', 'S8', 29851, 228);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Camaro', 25433, 488);
insert into car3 (make, model, price, person_id) values ('GMC', 'Acadia', 26681, 742);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Vibe', 43664, 873);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram Van 1500', 19146, 147);
insert into car3 (make, model, price, person_id) values ('Ford', 'F-Series', 8655, 696);
insert into car3 (make, model, price, person_id) values ('BMW', 'X5', 19575, 445);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B2600', 42875, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'CX-9', 38825, 936);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Caliber', 45186, null);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G', 31522, 531);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-5', null, 255);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Camaro', 35601, 806);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Suburban', 45626, 430);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Ciera', 32624, 236);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'G-Series 2500', 40643, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Town & Country', 13512, 103);
insert into car3 (make, model, price, person_id) values ('Volvo', 'C70', 19125, 296);
insert into car3 (make, model, price, person_id) values ('Honda', 'del Sol', 9938, 453);
insert into car3 (make, model, price, person_id) values ('Ford', 'Crown Victoria', 25105, 256);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 23574, 580);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 6680, 123);
insert into car3 (make, model, price, person_id) values ('Nissan', '240SX', 33893, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'E-Series', 43337, 692);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E250', 33740, 195);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Jetta III', 12741, 374);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', null, 281);
insert into car3 (make, model, price, person_id) values ('BMW', '3 Series', 8150, 146);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Topaz', 28433, 68);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'E-Class', 19522, 428);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Tribute', 12804, 168);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'MKZ', 45935, 834);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Continental Mark VII', 8269, 7);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Concorde', 11845, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Suburban 1500', 7180, 644);
insert into car3 (make, model, price, person_id) values ('Ford', 'Tempo', 35704, 206);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Pathfinder', 33796, 186);
insert into car3 (make, model, price, person_id) values ('Volvo', 'S70', 38413, 6);
insert into car3 (make, model, price, person_id) values ('GMC', 'Savana 2500', 27513, 94);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 25585, 624);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Continental Flying Spur', 35629, 808);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 2500', 48872, 241);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Monterey', 2970, 792);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 6481, 244);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Accent', 25044, 392);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Avenger', 16140, 755);
insert into car3 (make, model, price, person_id) values ('Chevrolet', '1500', 45923, 141);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sephia', 15520, 638);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Tiburon', 38157, 819);
insert into car3 (make, model, price, person_id) values ('Tesla', 'Roadster', 13595, 924);
insert into car3 (make, model, price, person_id) values ('Ford', 'Taurus', 17302, 613);
insert into car3 (make, model, price, person_id) values ('Ford', 'Bronco', 31137, 257);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'LeMans', 19213, 586);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Justy', 24526, 946);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Continental Mark VII', 30275, null);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Pathfinder', 14379, 628);
insert into car3 (make, model, price, person_id) values ('Audi', 'A3', 21260, 885);
insert into car3 (make, model, price, person_id) values ('Honda', 'Odyssey', 2911, 545);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Silhouette', 11454, null);
insert into car3 (make, model, price, person_id) values ('Alfa Romeo', '164', 43807, 155);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Eldorado', 3094, 794);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Boxster', 42021, 743);
insert into car3 (make, model, price, person_id) values ('Porsche', '928', null, 503);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 29875, 104);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 48404, 369);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Sequoia', null, 593);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'rio', 34064, 367);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota Club', 44652, 53);
insert into car3 (make, model, price, person_id) values ('Audi', 'A8', 45823, null);
insert into car3 (make, model, price, person_id) values ('Honda', 'Prelude', 49783, 892);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'C-Class', 27091, 524);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G', 37556, 715);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Town Car', 45071, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'D350', 6974, 877);
insert into car3 (make, model, price, person_id) values ('Porsche', '911', 43696, 537);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Venture', null, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 2500 Club', 38852, 209);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Lumina', null, 199);
insert into car3 (make, model, price, person_id) values ('Ford', 'F250', 29764, null);
insert into car3 (make, model, price, person_id) values ('Saturn', 'Aura', 21051, null);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Town Car', 14525, 532);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege', 7900, 219);
insert into car3 (make, model, price, person_id) values ('Ford', 'Edge', 29506, 109);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Sentra', 15137, 319);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', null, 892);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', 32511, 73);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'STS-V', 3156, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-3', 14964, 241);
insert into car3 (make, model, price, person_id) values ('Audi', 'S4', 32853, 747);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', null, 895);
insert into car3 (make, model, price, person_id) values ('Kia', 'Forte', 8153, 695);
insert into car3 (make, model, price, person_id) values ('Honda', 'CR-V', 26801, 677);
insert into car3 (make, model, price, person_id) values ('Audi', 'Quattro', 47957, 196);
insert into car3 (make, model, price, person_id) values ('Audi', 'Quattro', 39100, null);
insert into car3 (make, model, price, person_id) values ('Eagle', 'Summit', 42841, 826);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'APV', 42022, 44);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Vanagon', 3773, 654);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 3500', 15849, 679);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 15485, 891);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Neon', 17910, 194);
insert into car3 (make, model, price, person_id) values ('Tesla', 'Roadster', 37312, 891);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Prizm', 19979, 226);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Golf', 13660, 623);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Viper', 22039, 792);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Journey', 43939, 275);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'G-Class', null, 557);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Frontier', 41536, 453);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'LHS', 3507, 223);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tercel', 31916, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SLK-Class', null, 883);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Camry', 18125, 20);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 37660, 731);
insert into car3 (make, model, price, person_id) values ('GMC', 'Vandura 2500', 20353, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Sebring', null, 208);
insert into car3 (make, model, price, person_id) values ('Ford', 'F350', 2159, 667);
insert into car3 (make, model, price, person_id) values ('Hummer', 'H1', 5278, 350);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Miata MX-5', 21543, 36);
insert into car3 (make, model, price, person_id) values ('GMC', 'Suburban 1500', 9780, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Stratus', 35202, 370);
insert into car3 (make, model, price, person_id) values ('Smart', 'Fortwo', 32507, 527);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazdaspeed 3', 38131, 436);
insert into car3 (make, model, price, person_id) values ('Honda', 'Pilot', 8687, 406);
insert into car3 (make, model, price, person_id) values ('Buick', 'Skylark', 37844, 663);
insert into car3 (make, model, price, person_id) values ('Toyota', 'FJ Cruiser', 25240, 513);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 14142, 5);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 1504, 735);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 43068, 850);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 2266, 514);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Amigo', 42696, 793);
insert into car3 (make, model, price, person_id) values ('Ford', 'Mustang', 17218, 783);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 29977, 529);
insert into car3 (make, model, price, person_id) values ('Audi', 'A3', 33652, 648);
insert into car3 (make, model, price, person_id) values ('Ford', 'Ranger', 34409, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 5797, 449);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Grand Vitara', 20109, 140);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'G-Series G30', 9514, 173);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 3214, 37);
insert into car3 (make, model, price, person_id) values ('Lotus', 'Elise', 41012, 455);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', '3000GT', 49531, 32);
insert into car3 (make, model, price, person_id) values ('Honda', 'Pilot', 34319, 612);
insert into car3 (make, model, price, person_id) values ('Hummer', 'H2', 18217, null);
insert into car3 (make, model, price, person_id) values ('Honda', 'Prelude', 19868, 109);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'DeVille', 31743, null);
insert into car3 (make, model, price, person_id) values ('Volvo', 'V50', 32344, 253);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Maxima', 14988, 861);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Freelander', 21332, null);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 28268, 668);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Venture', 25779, 220);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Colorado', 35634, 791);
insert into car3 (make, model, price, person_id) values ('Audi', 'S4', 29572, 109);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 16035, 182);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Forenza', 4232, 867);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Silhouette', 31649, 310);
insert into car3 (make, model, price, person_id) values ('Lexus', 'RX Hybrid', 33920, 855);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Sonata', 27908, 324);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'QX', 35011, 181);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'EX', 10491, 459);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Malibu', 4886, null);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Stylus', 32603, 339);
insert into car3 (make, model, price, person_id) values ('Volvo', 'S60', null, 23);
insert into car3 (make, model, price, person_id) values ('GMC', 'Yukon XL 1500', 34256, 143);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Suburban 1500', 7991, 724);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'SJ', 37289, 793);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Elantra', null, 898);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Land Cruiser', 44719, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Taurus', 39458, 377);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'XJ', 32740, 414);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E350', 7165, 270);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SLS AMG', 19869, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B2600', 15560, 338);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', 44893, 100);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Cayenne', 46777, 658);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer', null, 214);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram Van 2500', 40543, 617);
insert into car3 (make, model, price, person_id) values ('Lotus', 'Elan', 33155, 887);
insert into car3 (make, model, price, person_id) values ('Audi', 'A3', 22080, 440);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Corolla', 27639, 431);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Yaris', 47470, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 19459, null);
insert into car3 (make, model, price, person_id) values ('Nissan', '350Z', 39769, 104);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Caravan', 47709, 947);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 6963, 303);
insert into car3 (make, model, price, person_id) values ('BMW', '5 Series', null, 585);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Justy', 2559, 386);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cavalier', 41967, 269);
insert into car3 (make, model, price, person_id) values ('Ferrari', 'California', 4420, 6);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Verona', 32813, 434);
insert into car3 (make, model, price, person_id) values ('Lexus', 'RX', 12087, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Pacifica', 45565, 935);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'G-Class', 49248, 413);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Tribeca', 14516, 754);
insert into car3 (make, model, price, person_id) values ('Audi', 'riolet', 22442, null);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'QX', 25222, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '190E', 49159, 255);
insert into car3 (make, model, price, person_id) values ('BMW', '325', null, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 30627, 859);
insert into car3 (make, model, price, person_id) values ('Honda', 'Passport', 46374, 438);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Pathfinder', 49965, 903);
insert into car3 (make, model, price, person_id) values ('Ford', 'C-MAX Hybrid', 34930, 168);
insert into car3 (make, model, price, person_id) values ('Volvo', 'V70', 38368, 228);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Neon', 3970, 738);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Mark VIII', null, 370);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Bonneville', 39150, 612);
insert into car3 (make, model, price, person_id) values ('BMW', '6 Series', 30123, 336);
insert into car3 (make, model, price, person_id) values ('Ford', 'Five Hundred', 3102, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'F-250 Super Duty', 48031, null);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 35064, 808);
insert into car3 (make, model, price, person_id) values ('Rolls-Royce', 'Ghost', 26869, 686);
insert into car3 (make, model, price, person_id) values ('Saturn', 'Aura', 45883, 546);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Trans Sport', 40743, 497);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-6', 41516, 329);
insert into car3 (make, model, price, person_id) values ('Buick', 'Skyhawk', 25677, 643);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram Van 3500', 44133, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'F-Series', 48357, null);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 18035, 568);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Quest', 2700, 231);
insert into car3 (make, model, price, person_id) values ('Acura', 'MDX', 30369, 330);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Concorde', 5666, 524);
insert into car3 (make, model, price, person_id) values ('Buick', 'Enclave', 30058, 214);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Murano', 18000, 377);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', 19435, 795);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Cayman', null, 503);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Capri', 42930, null);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'M', 25914, 328);
insert into car3 (make, model, price, person_id) values ('GMC', 'Jimmy', 10463, 640);
insert into car3 (make, model, price, person_id) values ('Mazda', '929', null, 942);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 7143, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sonoma Club Coupe', null, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Caprice', 48208, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Tahoe', 4134, 437);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Fiero', null, 340);
insert into car3 (make, model, price, person_id) values ('MINI', 'Cooper', 24509, 925);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazda6', 8480, 777);
insert into car3 (make, model, price, person_id) values ('BMW', '7 Series', 26386, 824);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'LS', 28011, 123);
insert into car3 (make, model, price, person_id) values ('BMW', 'Z4', 11057, null);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Grand Caravan', 33726, 782);
insert into car3 (make, model, price, person_id) values ('Ford', 'Expedition EL', 45737, 887);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Endeavor', 34839, 710);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 3500', 22563, null);
insert into car3 (make, model, price, person_id) values ('Acura', 'NSX', 1510, 641);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Mark VII', 3103, 857);
insert into car3 (make, model, price, person_id) values ('Scion', 'xB', 10972, 357);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado', 36485, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'F150', 20421, 101);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'E-Class', 13265, 319);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Villager', 8344, 356);
insert into car3 (make, model, price, person_id) values ('Ford', 'Thunderbird', 22240, 48);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 7854, 276);
insert into car3 (make, model, price, person_id) values ('Ford', 'Windstar', 28296, 447);
insert into car3 (make, model, price, person_id) values ('Ford', 'GT', 13573, 855);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Aveo', 44817, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Avalanche 2500', 12943, 705);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Concorde', 44977, 120);
insert into car3 (make, model, price, person_id) values ('Ford', 'E150', 13600, 598);
insert into car3 (make, model, price, person_id) values ('Lexus', 'SC', 9761, 916);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '500E', null, 252);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Avenger', 32610, 923);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Vibe', 36900, 823);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'Q', null, 518);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'XK', 48835, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SLK-Class', 32916, 919);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Scoupe', 1324, 861);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Miata MX-5', 47317, 90);
insert into car3 (make, model, price, person_id) values ('GMC', 'Yukon XL 2500', 44617, 113);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'DeVille', 11666, 774);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cobalt', 29120, 803);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Town Car', 6477, 802);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Paseo', 24687, 70);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Eclipse', 30803, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy XL', 17283, 783);
insert into car3 (make, model, price, person_id) values ('Acura', 'TL', 2101, 47);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '300TE', 27104, 722);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 45470, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer', 15766, 313);
insert into car3 (make, model, price, person_id) values ('Ford', 'Escort', 35221, 261);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 41372, 648);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Lynx', 6667, 910);
insert into car3 (make, model, price, person_id) values ('BMW', '330', 20826, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Fusion', 32127, 597);
insert into car3 (make, model, price, person_id) values ('Morgan', 'Aero 8', 33016, 384);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazdaspeed6', 28076, 672);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Trooper', null, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'TundraMax', 1084, 460);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', 21680, 136);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 3500', 47265, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Avalanche 2500', 5422, 398);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 1500', 10196, 843);
insert into car3 (make, model, price, person_id) values ('Subaru', 'SVX', 13287, 552);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Xterra', 24811, 157);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Supra', 16531, 645);
insert into car3 (make, model, price, person_id) values ('Ford', 'Taurus', 8614, null);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', 30343, 505);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E250', 34496, 570);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 3500', 3609, 305);
insert into car3 (make, model, price, person_id) values ('Ford', 'E150', 15808, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Marquis', 16337, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '190E', 16733, 945);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Sable', 46886, 309);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Grand Caravan', 22935, 296);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E250', 2961, 882);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Golf', 11008, 614);
insert into car3 (make, model, price, person_id) values ('Nissan', '370Z', 13776, 567);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 10907, 139);
insert into car3 (make, model, price, person_id) values ('Ford', 'Explorer Sport Trac', null, 294);
insert into car3 (make, model, price, person_id) values ('Audi', 'A6', 30266, 502);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Golf', null, null);
insert into car3 (make, model, price, person_id) values ('Honda', 'S2000', 5104, 585);
insert into car3 (make, model, price, person_id) values ('Alfa Romeo', 'Spider', 36051, 474);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Stealth', 22116, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Supra', 21826, 557);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Previa', 38487, 576);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 14508, 481);
insert into car3 (make, model, price, person_id) values ('Ford', 'Bronco', 37248, 872);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', 18199, 553);
insert into car3 (make, model, price, person_id) values ('Maybach', '62', 42553, 148);
insert into car3 (make, model, price, person_id) values ('Ford', 'Edge', null, 255);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'S10', 19627, 665);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Grand Caravan', 43165, 260);
insert into car3 (make, model, price, person_id) values ('Nissan', '370Z', 34514, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 14234, null);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Cube', 4987, 49);
insert into car3 (make, model, price, person_id) values ('Buick', 'Century', 19874, 412);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'S-Type', 13393, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'GS', 10700, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tundra', 2140, 287);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Sienna', 12294, 791);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', 38977, 785);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'J', 11187, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'V8', 49314, 79);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Frontier', 13281, 343);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Avalanche 1500', 3814, 840);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 3500HD', 26674, 168);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Bravada', 36121, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Corolla', 19652, 819);
insert into car3 (make, model, price, person_id) values ('Volvo', 'V70', 32481, 571);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'XK Series', 18891, 505);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Echo', 25583, 912);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Rodeo', 49609, 319);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Solstice', null, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Firebird', 29359, 352);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Impreza WRX', 21161, null);
insert into car3 (make, model, price, person_id) values ('Acura', 'Integra', 18925, 51);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SL-Class', 39450, 200);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Previa', null, 630);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', 22838, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'S6', 11515, 126);
insert into car3 (make, model, price, person_id) values ('Lexus', 'IS', 7834, 596);
insert into car3 (make, model, price, person_id) values ('Mazda', '323', 43545, null);
insert into car3 (make, model, price, person_id) values ('Kia', 'Optima', 23113, 280);
insert into car3 (make, model, price, person_id) values ('Geo', 'Metro', 39346, 148);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Corolla', 32572, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 2500', 44788, 60);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Golf', 49363, 918);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Mighty Max Macro', 48782, 12);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LS', null, null);
insert into car3 (make, model, price, person_id) values ('Acura', 'SLX', 12557, 227);
insert into car3 (make, model, price, person_id) values ('Studebaker', 'Avanti', 14113, 399);
insert into car3 (make, model, price, person_id) values ('Ram', '3500', 8661, 246);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Liberty', 46780, 106);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Tiburon', 3280, null);
insert into car3 (make, model, price, person_id) values ('Kia', 'Spectra', 18606, null);
insert into car3 (make, model, price, person_id) values ('BMW', 'M3', 48722, null);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Wrangler', 49035, 667);
insert into car3 (make, model, price, person_id) values ('Ford', 'Expedition EL', 32394, null);
insert into car3 (make, model, price, person_id) values ('Jaguar', 'XJ Series', 36674, 662);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Alcyone SVX', 15996, 839);
insert into car3 (make, model, price, person_id) values ('Lamborghini', 'Diablo', 30378, 363);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', '98', null, 68);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Golf', 42325, 292);
insert into car3 (make, model, price, person_id) values ('GMC', 'Rally Wagon 2500', 18551, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Vibe', 20712, 465);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 45646, 623);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Patriot', 33996, 13);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express 2500', null, 214);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sportage', 39397, 151);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', null, 494);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Eurovan', null, 873);
insert into car3 (make, model, price, person_id) values ('Buick', 'Coachbuilder', 20299, 103);
insert into car3 (make, model, price, person_id) values ('Lexus', 'RX', 39395, 17);
insert into car3 (make, model, price, person_id) values ('Ford', 'Aerostar', 2993, 821);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege5', 21420, 353);
insert into car3 (make, model, price, person_id) values ('Ford', 'Taurus', 40572, 3);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Escalade', 13096, 598);
insert into car3 (make, model, price, person_id) values ('Hummer', 'H1', 39355, 289);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 32425, 99);
insert into car3 (make, model, price, person_id) values ('MINI', 'MINI', 21627, 387);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Outlander', 9043, 14);
insert into car3 (make, model, price, person_id) values ('Smart', 'Fortwo', 28797, 504);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazdaspeed 3', 20879, 270);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Sunbird', 41419, null);
insert into car3 (make, model, price, person_id) values ('GMC', '2500 Club Coupe', 26016, 922);
insert into car3 (make, model, price, person_id) values ('Audi', 'A4', 2872, 486);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', 10286, 377);
insert into car3 (make, model, price, person_id) values ('Audi', 'S6', 2586, 860);
insert into car3 (make, model, price, person_id) values ('BMW', 'M', 11866, 24);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Tribute', 46266, 144);
insert into car3 (make, model, price, person_id) values ('Ford', 'E-Series', 12832, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mountaineer', 21413, 215);
insert into car3 (make, model, price, person_id) values ('Acura', 'RDX', 38411, 52);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Ciera', 18479, 283);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Frontier', 9096, 620);
insert into car3 (make, model, price, person_id) values ('GMC', 'Envoy', 26142, 924);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', 22867, 716);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'QX', 29443, null);
insert into car3 (make, model, price, person_id) values ('Jeep', 'Grand Cherokee', 23578, 441);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Mazdaspeed 3', 2544, 106);
insert into car3 (make, model, price, person_id) values ('Honda', 'Odyssey', 25572, 518);
insert into car3 (make, model, price, person_id) values ('Acura', 'TSX', 13027, 620);
insert into car3 (make, model, price, person_id) values ('BMW', '6 Series', 49471, 330);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 2500', 33308, 457);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Esteem', 18626, 939);
insert into car3 (make, model, price, person_id) values ('Daewoo', 'Nubira', 16176, 252);
insert into car3 (make, model, price, person_id) values ('Mazda', 'RX-7', 37291, 916);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', '3000GT', 31968, 126);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Matrix', null, 893);
insert into car3 (make, model, price, person_id) values ('Nissan', '240SX', 20883, 508);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram Van 3500', 29704, 571);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Boxster', null, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Express 1500', 6309, 904);
insert into car3 (make, model, price, person_id) values ('Geo', 'Prizm', 35923, 819);
insert into car3 (make, model, price, person_id) values ('Ford', 'Taurus', 29684, null);
insert into car3 (make, model, price, person_id) values ('Bentley', 'Continental Flying Spur', 14358, 365);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Maxima', 26932, null);
insert into car3 (make, model, price, person_id) values ('Audi', '200', 34640, 255);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Allante', 18827, 427);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G', 42449, 139);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', 20294, 330);
insert into car3 (make, model, price, person_id) values ('Acura', 'RDX', 49951, 189);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 21643, 167);
insert into car3 (make, model, price, person_id) values ('Acura', 'RSX', 17944, 892);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Escalade EXT', null, 915);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Blazer', 47434, 318);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'SL-Class', null, 81);
insert into car3 (make, model, price, person_id) values ('Toyota', '4Runner', 18013, 291);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege', 32247, 202);
insert into car3 (make, model, price, person_id) values ('Toyota', 'FJ Cruiser', 47233, 296);
insert into car3 (make, model, price, person_id) values ('Mazda', 'RX-7', 45533, 510);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Neon', 23270, 483);
insert into car3 (make, model, price, person_id) values ('Mazda', 'Protege', null, 676);
insert into car3 (make, model, price, person_id) values ('Mazda', '626', 19002, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'Q7', 30577, 462);
insert into car3 (make, model, price, person_id) values ('Subaru', 'SVX', 37546, 714);
insert into car3 (make, model, price, person_id) values ('Volvo', 'C70', 48872, 776);
insert into car3 (make, model, price, person_id) values ('Ford', 'Thunderbird', 31657, null);
insert into car3 (make, model, price, person_id) values ('Acura', 'MDX', 48932, 764);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Blazer', 14418, 148);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LS', 46191, 939);
insert into car3 (make, model, price, person_id) values ('Volvo', 'XC90', 39821, 471);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'SRX', 10201, 563);
insert into car3 (make, model, price, person_id) values ('Volvo', 'S60', null, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Sebring', null, null);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Alcyone SVX', 47901, 516);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MPV', 48745, null);
insert into car3 (make, model, price, person_id) values ('Lexus', 'ES', 37534, null);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 21992, 685);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Expo', 22805, 338);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Am', 34555, 811);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Pajero', null, 884);
insert into car3 (make, model, price, person_id) values ('BMW', '3 Series', null, 673);
insert into car3 (make, model, price, person_id) values ('Audi', 'RS 4', 31650, 689);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Freelander', 45871, 840);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Continental Mark VII', 42508, 600);
insert into car3 (make, model, price, person_id) values ('Fiat', 'Nuova 500', 2922, 259);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'G-Series G30', 19620, 173);
insert into car3 (make, model, price, person_id) values ('Kia', 'Spectra', 1570, 452);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', null, null);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra', 48765, 251);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Cabriolet', 41325, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', 'S-Class', 45242, 908);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Avenger', 15380, 571);
insert into car3 (make, model, price, person_id) values ('Nissan', '300ZX', 40783, 350);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Starion', 11254, null);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Azera', 28160, 486);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'Continental', 47083, 644);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B-Series', null, 698);
insert into car3 (make, model, price, person_id) values ('Plymouth', 'Sundance', null, 764);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Tiburon', 49993, null);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'CC', 3139, 761);
insert into car3 (make, model, price, person_id) values ('Volvo', 'XC90', 26018, 211);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-3', 28273, 338);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Touareg', 46345, 855);
insert into car3 (make, model, price, person_id) values ('Audi', 'A4', 3278, 715);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Altima', 3916, 563);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Colt', 7970, 797);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 34539, 284);
insert into car3 (make, model, price, person_id) values ('Lamborghini', 'Gallardo', 19161, 944);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Avalon', 39735, 767);
insert into car3 (make, model, price, person_id) values ('Nissan', 'NV1500', 42593, 680);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tacoma Xtra', 9031, 868);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Chariot', 23806, 857);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cruze', 28562, 417);
insert into car3 (make, model, price, person_id) values ('Saab', '9000', 42903, 77);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cobalt SS', 32546, 907);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Tracer', 27062, 907);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Uplander', 1762, 937);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'SSR', 49154, 531);
insert into car3 (make, model, price, person_id) values ('Volvo', 'XC70', null, 796);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E150', 3701, 507);
insert into car3 (make, model, price, person_id) values ('Lincoln', 'MKS', 23085, 275);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Grand Caravan', 22221, 120);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'Q', 10926, 555);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Tiburon', 23973, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Camry', 20156, 925);
insert into car3 (make, model, price, person_id) values ('Saturn', 'S-Series', 8803, 868);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Cayman', 39780, 718);
insert into car3 (make, model, price, person_id) values ('GMC', 'Suburban 2500', 43903, 822);
insert into car3 (make, model, price, person_id) values ('Honda', 'Odyssey', 22547, null);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Tredia', 36300, null);
insert into car3 (make, model, price, person_id) values ('Mercedes-Benz', '300SD', 35345, 520);
insert into car3 (make, model, price, person_id) values ('Ford', 'Tempo', 15021, 922);
insert into car3 (make, model, price, person_id) values ('Ford', 'Econoline E250', 17603, 207);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Chariot', null, 511);
insert into car3 (make, model, price, person_id) values ('Eagle', 'Vision', 41321, null);
insert into car3 (make, model, price, person_id) values ('Audi', 'A6', 28888, 600);
insert into car3 (make, model, price, person_id) values ('Nissan', '370Z', 43132, 330);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Justy', 15356, 459);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Silverado 2500', 24963, 463);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Aerio', null, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Corvette', 20697, null);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Camry Solara', 17808, 328);
insert into car3 (make, model, price, person_id) values ('Ford', 'F-Series', 40916, null);
insert into car3 (make, model, price, person_id) values ('Honda', 'Civic', 30368, 224);
insert into car3 (make, model, price, person_id) values ('GMC', 'Jimmy', null, 294);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Tracker', 21624, 359);
insert into car3 (make, model, price, person_id) values ('Volvo', 'V70', 3720, 59);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Viper', 33881, 317);
insert into car3 (make, model, price, person_id) values ('Honda', 'Odyssey', 48443, 309);
insert into car3 (make, model, price, person_id) values ('Toyota', 'T100', null, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Sunfire', 9000, 585);
insert into car3 (make, model, price, person_id) values ('MINI', 'Cooper Clubman', 1226, 413);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sedona', 21041, 10);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Discovery', 28801, 49);
insert into car3 (make, model, price, person_id) values ('Audi', 'RS4', 2133, 559);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Raider', 13091, 547);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Grand Marquis', 13960, 591);
insert into car3 (make, model, price, person_id) values ('Volvo', 'S60', 49152, null);
insert into car3 (make, model, price, person_id) values ('Mazda', 'B-Series Plus', 27972, 829);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tacoma', 39843, 797);
insert into car3 (make, model, price, person_id) values ('Ford', 'LTD Crown Victoria', 40402, null);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Camaro', 3741, 252);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Elantra', 41251, 292);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Expo LRV', 23204, 644);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'GLI', 6359, 465);
insert into car3 (make, model, price, person_id) values ('Ford', 'Mustang', 1492, 289);
insert into car3 (make, model, price, person_id) values ('Austin', 'Mini Cooper', 36619, 482);
insert into car3 (make, model, price, person_id) values ('BMW', 'M', 19238, 573);
insert into car3 (make, model, price, person_id) values ('Acura', 'Legend', 27206, 660);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sportage', 16792, 387);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'Seville', 37928, null);
insert into car3 (make, model, price, person_id) values ('Kia', 'Sedona', 21691, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Mustang', 46420, null);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Routan', 20427, 843);
insert into car3 (make, model, price, person_id) values ('GMC', 'Sierra 2500', 34412, 482);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Villager', 2619, 395);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Corrado', 33443, 734);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Charger', 2174, 791);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Baja', 15608, null);
insert into car3 (make, model, price, person_id) values ('Ford', 'Edge', 47732, 456);
insert into car3 (make, model, price, person_id) values ('Acura', 'Integra', 25898, 73);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'CC', 5747, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Villager', 46265, 198);
insert into car3 (make, model, price, person_id) values ('Aston Martin', 'DB9', 34384, null);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'STS', null, 430);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Titan', 8247, null);
insert into car3 (make, model, price, person_id) values ('Lotus', 'Esprit Turbo', 15330, 456);
insert into car3 (make, model, price, person_id) values ('Isuzu', 'Axiom', null, 459);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'Sebring', 18133, 219);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Galant', 32623, 456);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'M', 27664, 537);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Dakota', 16919, 748);
insert into car3 (make, model, price, person_id) values ('Cadillac', 'DeVille', 21038, 356);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'HHR', null, 480);
insert into car3 (make, model, price, person_id) values ('Volkswagen', 'Cabriolet', 12201, 111);
insert into car3 (make, model, price, person_id) values ('Lexus', 'RX', 31783, 627);
insert into car3 (make, model, price, person_id) values ('BMW', '550', 15954, 570);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G25', 5089, 757);
insert into car3 (make, model, price, person_id) values ('Smart', 'Fortwo', 6501, 615);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Classic', 33274, 918);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Tiburon', 3807, 238);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Murano', 2605, 3);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'Q', 48726, null);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Toronado', 23742, 613);
insert into car3 (make, model, price, person_id) values ('Ford', 'Mustang', 41086, null);
insert into car3 (make, model, price, person_id) values ('Infiniti', 'G', 23846, 81);
insert into car3 (make, model, price, person_id) values ('Maybach', '57S', 45896, null);
insert into car3 (make, model, price, person_id) values ('Suzuki', 'Esteem', 11373, null);
insert into car3 (make, model, price, person_id) values ('Kia', 'Rio', 35853, null);
insert into car3 (make, model, price, person_id) values ('Mercury', 'Mountaineer', 34939, 841);
insert into car3 (make, model, price, person_id) values ('Subaru', 'Forester', 28846, 219);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'GTO', 28935, 534);
insert into car3 (make, model, price, person_id) values ('Ford', 'E350', 47125, 110);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Cavalier', 38638, 593);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'GTO', 15360, 694);
insert into car3 (make, model, price, person_id) values ('Buick', 'LaCrosse', 34092, 893);
insert into car3 (make, model, price, person_id) values ('Toyota', 'Tercel', 33226, 927);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram Van 1500', null, 832);
insert into car3 (make, model, price, person_id) values ('Subaru', 'BRZ', 1780, 568);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'Chariot', 17212, 87);
insert into car3 (make, model, price, person_id) values ('Audi', 'A5', null, 322);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Blazer', 22575, 801);
insert into car3 (make, model, price, person_id) values ('Nissan', 'Maxima', 28091, null);
insert into car3 (make, model, price, person_id) values ('Land Rover', 'Range Rover', 5447, 898);
insert into car3 (make, model, price, person_id) values ('Ford', 'Escort', 27883, 147);
insert into car3 (make, model, price, person_id) values ('Ford', 'Bronco II', 46760, 148);
insert into car3 (make, model, price, person_id) values ('Dodge', 'Ram 1500', 15211, 220);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 36628, null);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 42074, null);
insert into car3 (make, model, price, person_id) values ('Honda', 'Element', 40151, null);
insert into car3 (make, model, price, person_id) values ('Porsche', 'Cayenne', null, 492);
insert into car3 (make, model, price, person_id) values ('Buick', 'Park Avenue', 25267, 100);
insert into car3 (make, model, price, person_id) values ('Honda', 'Prelude', 6783, 266);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Trans Sport', 16252, 590);
insert into car3 (make, model, price, person_id) values ('Toyota', '4Runner', 32689, 576);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Firebird', 34585, 481);
insert into car3 (make, model, price, person_id) values ('Ford', 'Club Wagon', 49737, 735);
insert into car3 (make, model, price, person_id) values ('Mazda', 'MX-6', 33030, 937);
insert into car3 (make, model, price, person_id) values ('Saturn', 'S-Series', 42566, 597);
insert into car3 (make, model, price, person_id) values ('Lexus', 'LX', 17061, 95);
insert into car3 (make, model, price, person_id) values ('Oldsmobile', 'Achieva', 11377, 887);
insert into car3 (make, model, price, person_id) values ('Pontiac', 'Grand Prix', 7242, 906);
insert into car3 (make, model, price, person_id) values ('Mitsubishi', 'L300', 27419, 350);
insert into car3 (make, model, price, person_id) values ('Buick', 'LaCrosse', 19902, 335);
insert into car3 (make, model, price, person_id) values ('Audi', 'RS 4', 4362, null);
insert into car3 (make, model, price, person_id) values ('Hyundai', 'Santa Fe', null, null);
insert into car3 (make, model, price, person_id) values ('Chrysler', 'New Yorker', 43142, 785);
insert into car3 (make, model, price, person_id) values ('Chevrolet', 'Prizm', 12610, null);

ALTER TABLE car3 ADD CONSTRAINT for_key_for_car3 FOREIGN KEY (person_id) REFERENCES person3(person_id);