-- #Setting up a sample table
DROP TABLE IF EXISTS accounts;

SELECT * FROM accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);

-- #Begin a transaction
INSERT INTO accounts(name,balance)
VALUES('Bob',10000);

-- #PostgreSQL inserted
-- #a new row into the accounts table immediately.
-- #In this case, you do not know when the
-- #transaction begins and cannot intercept the
-- #modification such as rolling it back.


SELECT * FROM accounts;

BEGIN;

INSERT INTO accounts(name,balance)
VALUES('Alice',10000);

-- #if you finish the session and see the result,
-- #updates are not applied.

-- Commit a transaction
BEGIN;

INSERT INTO accounts(name,balance)
VALUES('Alice',10000);

COMMIT;

BEGIN;

INSERT INTO accounts(name, balance)
VALUES('Zhassurbek', 2000000);

select * from accounts;

commit;

BEGIN;

INSERT INTO accounts(name, balance)
VALUES ('Muhammad', 30000);


select * from accounts;

rollback;